In [3]:
import numpy as np

1

In [7]:
a = np.arange(1, 11)

In [8]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2

In [9]:
a = np.zeros((3, 3))

In [10]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3

In [11]:
a = np.random.randint(low=1, high=11, size=(5, 5))

In [12]:
print(a)

[[ 3  5  4  7  7]
 [10  7  4  7 10]
 [ 5  7  1  2 10]
 [ 1  1  4  5  6]
 [10  9  2  3  3]]


4

In [13]:
a = np.random.random((4, 4))

In [14]:
print(a)

[[0.19541156 0.69865727 0.77715492 0.56728221]
 [0.82580942 0.84560783 0.14767358 0.84770765]
 [0.46431134 0.9590067  0.77770563 0.72096387]
 [0.5552123  0.84655995 0.67630763 0.23321119]]


5

In [15]:
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)

In [16]:
add = a + b

In [17]:
sub = a - b

In [18]:
mul = a * b

In [19]:
print("a:", a)
print("b:", b)
print("add:", add)
print("sub:", sub)
print("mul:", mul)

a: [6 3 8 2 6]
b: [ 7 10  6  4  9]
add: [13 13 14  6 15]
sub: [-1 -7  2 -2 -3]
mul: [42 30 48  8 54]


6

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])

In [21]:
result = np.dot(a, b)

In [22]:
print(result)

84


7

In [23]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))

In [24]:
result = np.dot(a, b)

In [25]:
print(result)

[[83 53 23]
 [69 82 28]]


8

In [27]:
a = np.random.randint(1, 11, size=(3, 3))
b = np.linalg.inv(a)

In [29]:
print("Матриця:")
print(a)
print("Обернена матриця:")
print(b)

Матриця:
[[1 9 8]
 [6 3 8]
 [7 6 2]]
Обернена матриця:
[[-0.08860759  0.06329114  0.10126582]
 [ 0.092827   -0.11392405  0.08438819]
 [ 0.03164557  0.12025316 -0.10759494]]


9

In [31]:
a = np.random.random((4, 4))
b = np.transpose(a)

In [32]:
print(b)

[[0.5943029  0.4397848  0.20155326 0.66967832]
 [0.87696858 0.26369881 0.29135612 0.59369591]
 [0.07130174 0.74156711 0.63183209 0.66336858]
 [0.67367888 0.46624846 0.53199466 0.37365832]]


10

In [34]:
a = np.random.randint(1, 11, (3, 4))
b = np.random.randint(1, 11, 4)

In [35]:
result = np.dot(a, b)

In [36]:
print("Матриця:")
print(a)
print("Вектор:", b)
print("Результат:", result)

Матриця:
[[ 5 10  7  3]
 [ 8  7  6  1]
 [ 2  8  5  9]]
Вектор: [ 3  2 10  7]
Результат: [126 105 135]


11

In [37]:
a = np.random.random((2, 3))
b = np.random.random(3)

In [38]:
result = np.dot(a, b)

In [39]:
print(result)

[1.68942194 1.01354094]


12

In [40]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
result = a * b

In [41]:
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)
print("Результат множення:")
print(result)

Перша матриця:
[[1 5]
 [7 7]]
Друга матриця:
[[2 6]
 [9 1]]
Результат множення:
[[ 2 30]
 [63  7]]


13

In [42]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

In [43]:
result = np.dot(a, b)

In [44]:
print(result)

[[47 31]
 [52 34]]


14

In [4]:
a = np.random.randint(1, 101, size=(5, 5))

In [5]:
b = np.sum(a)

In [6]:
print("Сума елементів матриці: ", b)

Сума елементів матриці:  1509


15

In [7]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))

In [8]:
result = a - b

In [9]:
print(result)

[[-1  7  4  2]
 [ 0 -3  0  6]
 [ 0 -8  0  2]
 [-6  2  0  4]]


16

In [10]:
a = np.random.random((3, 3))

In [11]:
b = np.sum(a, axis=1, keepdims=True)

In [12]:
print("Матриця:\n", a)
print("Вектор-стовпчик сум елементів кожного рядка матриці:\n", b)

Матриця:
 [[0.59792447 0.42521342 0.5016911 ]
 [0.66974636 0.71485652 0.34469531]
 [0.02781334 0.31179339 0.86329251]]
Вектор-стовпчик сум елементів кожного рядка матриці:
 [[1.52482899]
 [1.72929819]
 [1.20289924]]


17

In [13]:
a = np.random.randint(1, 10, size=(3, 4))

In [14]:
b = a ** 2

In [ ]:
print("Початкова матриця:\n", a)
print("Матриця з квадратами чисел:\n", b)

18

In [15]:
a = np.random.randint(1, 51, size=4)

In [16]:
b = np.sqrt(a)

In [17]:
print("Випадковий вектор:", a)
print("Вектор з квадратними коренями:", b)

Випадковий вектор: [29 22 18 21]
Вектор з квадратними коренями: [5.38516481 4.69041576 4.24264069 4.58257569]
